import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { api } from '../App';
import { toast } from 'sonner';
import { Code, Zap, Target, TrendingUp, Sparkles, ChevronRight } from 'lucide-react';

const HomePage = ({ currentUser, loginUser, logoutUser }) => {
  const navigate = useNavigate();
  const [showAuthDialog, setShowAuthDialog] = useState(false);
  const [isLogin, setIsLogin] = useState(false);
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    skill_level: 'beginner',
  });
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (isLogin) {
        // For login, we'll search for user by username
        const response = await api.get('/users');
        const user = response.data.find(u => u.username === formData.username);
        
        if (user) {
          loginUser(user);
          toast.success('Welcome back!');
          navigate('/dashboard');
        } else {
          toast.error('User not found. Please sign up first.');
        }
      } else {
        // Sign up - create new user
        const response = await api.post('/users', formData);
        loginUser(response.data);
        toast.success('Account created successfully!');
        navigate('/dashboard');
      }
    } catch (error) {
      console.error('Auth error:', error);
      toast.error(error.response?.data?.detail || 'Authentication failed');
    } finally {
      setLoading(false);
    }
  };

  if (currentUser) {
    navigate('/dashboard');
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
      {/* Navigation */}
      <nav className="border-b bg-white/80 backdrop-blur-md sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center space-x-2">
            <Code className="h-8 w-8 text-indigo-600" />
            <span className="text-2xl font-bold gradient-text">DSA Forge</span>
          </div>
          <Button onClick={() => setShowAuthDialog(true)} size="lg" data-testid="nav-get-started-btn">
            Get Started <ChevronRight className="ml-2 h-4 w-4" />
          </Button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-20 text-center" data-testid="hero-section">
        <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn">
          <div className="inline-flex items-center space-x-2 bg-indigo-100 text-indigo-700 px-4 py-2 rounded-full text-sm font-medium">
            <Sparkles className="h-4 w-4" />
            <span>AI-Powered Learning Platform</span>
          </div>
          
          <h1 className="text-6xl font-bold leading-tight">
            Master DSA with
            <span className="gradient-text"> AI-Generated</span>
            <br />Personalized Roadmaps
          </h1>
          
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Transform your coding journey with intelligent, adaptive learning paths tailored to your skill level and goals.
          </p>
          
          <div className="flex justify-center space-x-4">
            <Button size="lg" onClick={() => setShowAuthDialog(true)} className="text-lg px-8 py-6" data-testid="hero-get-started-btn">
              Start Learning Free <ChevronRight className="ml-2 h-5 w-5" />
            </Button>
            <Button size="lg" variant="outline" className="text-lg px-8 py-6" data-testid="hero-view-problems-btn"
              onClick={() => navigate('/problems')}>
              View Problems
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-6 py-20" data-testid="features-section">
        <h2 className="text-4xl font-bold text-center mb-12">Why Choose DSA Forge?</h2>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <Card className="card-hover border-2" data-testid="feature-ai-powered">
            <CardHeader>
              <Zap className="h-12 w-12 text-indigo-600 mb-4" />
              <CardTitle>AI-Powered</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">Get personalized learning paths generated by advanced AI based on your skill level and goals.</p>
            </CardContent>
          </Card>

          <Card className="card-hover border-2" data-testid="feature-structured-path">
            <CardHeader>
              <Target className="h-12 w-12 text-purple-600 mb-4" />
              <CardTitle>Structured Path</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">Follow a clear, week-by-week roadmap designed to build your skills progressively.</p>
            </CardContent>
          </Card>

          <Card className="card-hover border-2" data-testid="feature-track-progress">
            <CardHeader>
              <TrendingUp className="h-12 w-12 text-green-600 mb-4" />
              <CardTitle>Track Progress</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">Monitor your learning journey with detailed analytics and completion statistics.</p>
            </CardContent>
          </Card>

          <Card className="card-hover border-2" data-testid="feature-curated-problems">
            <CardHeader>
              <Code className="h-12 w-12 text-blue-600 mb-4" />
              <CardTitle>Curated Problems</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">Access a comprehensive library of hand-picked DSA problems from easy to hard.</p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-6 py-20" data-testid="cta-section">
        <Card className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white border-0">
          <CardContent className="py-16 text-center">
            <h2 className="text-4xl font-bold mb-4">Ready to Start Your Journey?</h2>
            <p className="text-xl mb-8 opacity-90">Join thousands of developers mastering DSA with AI-powered roadmaps</p>
            <Button size="lg" variant="secondary" className="text-lg px-8 py-6" onClick={() => setShowAuthDialog(true)} data-testid="cta-get-started-btn">
              Get Started Now <ChevronRight className="ml-2 h-5 w-5" />
            </Button>
          </CardContent>
        </Card>
      </section>

      {/* Footer */}
      <footer className="border-t bg-white py-8">
        <div className="container mx-auto px-6 text-center text-gray-600">
          <p>© 2026 DSA Forge. Built with ❤️ for developers.</p>
        </div>
      </footer>

      {/* Auth Dialog */}
      <Dialog open={showAuthDialog} onOpenChange={setShowAuthDialog}>
        <DialogContent className="sm:max-w-md" data-testid="auth-dialog">
          <DialogHeader>
            <DialogTitle>{isLogin ? 'Welcome Back' : 'Create Your Account'}</DialogTitle>
            <DialogDescription>
              {isLogin ? 'Enter your username to continue' : 'Start your DSA learning journey today'}
            </DialogDescription>
          </DialogHeader>
          
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label htmlFor="username">Username</Label>
              <Input
                id="username"
                data-testid="auth-username-input"
                value={formData.username}
                onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                required
                placeholder="Enter your username"
              />
            </div>
            
            {!isLogin && (
              <>
                <div>
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    data-testid="auth-email-input"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    required
                    placeholder="your.email@example.com"
                  />
                </div>
                
                <div>
                  <Label htmlFor="skill_level">Skill Level</Label>
                  <Select
                    value={formData.skill_level}
                    onValueChange={(value) => setFormData({ ...formData, skill_level: value })}
                  >
                    <SelectTrigger data-testid="auth-skill-select">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="beginner">Beginner</SelectItem>
                      <SelectItem value="intermediate">Intermediate</SelectItem>
                      <SelectItem value="advanced">Advanced</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </>
            )}
            
            <Button type="submit" className="w-full" disabled={loading} data-testid="auth-submit-btn">
              {loading ? 'Processing...' : (isLogin ? 'Login' : 'Sign Up')}
            </Button>
          </form>
          
          <div className="text-center text-sm">
            <button
              type="button"
              onClick={() => setIsLogin(!isLogin)}
              className="text-indigo-600 hover:underline"
              data-testid="auth-toggle-btn"
            >
              {isLogin ? "Don't have an account? Sign up" : 'Already have an account? Login'}
            </button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default HomePage;